name: presensi
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  firebase_core: 2.9.0
  firebase_auth: 4.4.0
  cloud_firestore: 4.5.0
  firebase_storage: 11.1.0
  convex_bottom_bar: 3.0.0
  persistent_bottom_nav_bar: ^5.0.2
  intl: 0.17.0
  geolocator: 9.0.2
  geocoding: 2.1.0
  syncfusion_flutter_datepicker: 20.4.44
  image_picker: 0.8.7+4
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: launcher_icon
  image_path: assets/icon.png
  ios: true

flutter:
  assets:
    - images/logostmikamikbandung.jpg
  uses-material-design: true
